### ISSUE TITLE
Revisar Inserción de imágenes en tinyMCE

### ISSUE THREAD

**Issue by BertaOctech** [carcam/bugsbusters#1]
¿Existe un vínculo entre el media manager y MCE para poder cargar la imagen??

En imagen & links sí ofrece media manager, upload image etc

**Comment by carcam** [comment]
@BertaOctech tienes que usar la opción de "CMS Content" para ello:

![Captura de pantalla 2020-11-13 a las 6 17 09](https://user-images.githubusercontent.com/1695138/99031657-eba92980-2577-11eb-9933-a4bb36162ba1.png)

**Comment by BertaOctech** [comment]
Ah!! Curioso,
